package com.testsp.data;

// Generated 11-May-2015 01:30:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", schema = "public")
public class Student implements java.io.Serializable {

	private int stuId;
	private Teacher teacher;
	private String stuName;

	public Student() {
	}

	public Student(int stuId, Teacher teacher) {
		this.stuId = stuId;
		this.teacher = teacher;
	}

	public Student(int stuId, Teacher teacher, String stuName) {
		this.stuId = stuId;
		this.teacher = teacher;
		this.stuName = stuName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "stu_id", unique = true, nullable = false)
	public int getStuId() {
		return this.stuId;
	}

	public void setStuId(int stuId) {
		this.stuId = stuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tea_id", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "stu_name")
	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

}
