package com.testsp.data;

// Generated 11-May-2015 01:30:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", schema = "public")
public class Teacher implements java.io.Serializable {

	
	private int teaId;
	private String teaName;
	private Set<Student> students = new HashSet<Student>(0);

	public Teacher() {
	}

	public Teacher(int teaId) {
		this.teaId = teaId;
	}

	public Teacher(int teaId, String teaName, Set<Student> students) {
		this.teaId = teaId;
		this.teaName = teaName;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "tea_id", unique = true, nullable = false)
	public int getTeaId() {
		return this.teaId;
	}

	public void setTeaId(int teaId) {
		this.teaId = teaId;
	}

	@Column(name = "tea_name")
	public String getTeaName() {
		return this.teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
